In [20]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
import numpy as np

In [21]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

labels = np.array( [1,1,1,1,1,0,0,0,0,0])


#Assign each word an unique number upto vocab_size

In [22]:
vocab_size = 100
encoded_docs =[ one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[41, 82], [94, 5], [10, 69], [86, 5], [75], [19], [54, 69], [82, 94], [54, 5], [37, 14, 82, 40]]


In [26]:
max_length = 4
padded_docs  = pad_sequences(encoded_docs,maxlen = max_length,padding = 'post')
print(padded_docs)

[[41 82  0  0]
 [94  5  0  0]
 [10 69  0  0]
 [86  5  0  0]
 [75  0  0  0]
 [19  0  0  0]
 [54 69  0  0]
 [82 94  0  0]
 [54  5  0  0]
 [37 14 82 40]]


In [27]:
from os import name
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, name='Embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_11 (Flatten)            │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [28]:
model.fit(padded_docs,labels,epochs=50,verbose=0)

In [29]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000
